//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_Head_New
    {
        public Nullable<double> AcntCode { get; set; }
        public string description { get; set; }
        public string MainAccount { get; set; }
        public string SubAccount { get; set; }
        public string ControlAccount { get; set; }
        public string AcntName { get; set; }
        public string AcntId { get; set; }
        public Nullable<double> Debit { get; set; }
        public Nullable<double> Credit { get; set; }
        public Nullable<double> Balance { get; set; }
        public int Id { get; set; }
    }
}
