//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string AcntId { get; set; }
        public string Dscr { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public Nullable<decimal> Dr { get; set; }
        public Nullable<decimal> Cr { get; set; }
        public int Levels { get; set; }
        public Nullable<int> Balance { get; set; }
        public string GAcntId { get; set; }
        public string SGAcntId { get; set; }
        public string SubAcntId { get; set; }
        public string USubAcntId { get; set; }
        public int Status { get; set; }
        public int CompNo { get; set; }
        public Nullable<decimal> TotOpenBal { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public System.DateTime SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
        public decimal ObDr { get; set; }
        public decimal ObCr { get; set; }
    }
}
