//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountInfo
    {
        public string Id { get; set; }
        public string CachAc { get; set; }
        public string ExcDutyAc { get; set; }
        public string CreditSaleAc { get; set; }
        public string SaleReturnAc { get; set; }
        public string ExportAc { get; set; }
        public string SaleTaxPAc { get; set; }
        public string SaleTaxRAc { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<int> CompNo { get; set; }
        public Nullable<int> BranchNo { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
    }
}
