//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountsBackUp
    {
        public string AcntId { get; set; }
        public string Dscr { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public Nullable<decimal> Dr { get; set; }
        public Nullable<decimal> Cr { get; set; }
        public Nullable<int> Levels { get; set; }
        public string GAcntId { get; set; }
        public string GAsstDscr { get; set; }
        public string SGAcntId { get; set; }
        public string SGADscr { get; set; }
        public string SubAcntId { get; set; }
        public string SubADscr { get; set; }
        public string USubAcntId { get; set; }
        public string USubDscr { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> Diff { get; set; }
        public Nullable<decimal> ChargBal { get; set; }
        public Nullable<decimal> ExpBal { get; set; }
        public int Status { get; set; }
        public int CompNo { get; set; }
        public Nullable<decimal> TotOpenBal { get; set; }
        public Nullable<decimal> TotDr { get; set; }
        public Nullable<decimal> TotCr { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public int DeletionID { get; set; }
    }
}
