//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountsOpeningBalance
    {
        public string OpeningBalanceID { get; set; }
        public Nullable<int> OpeningBalanceNo { get; set; }
        public Nullable<System.DateTime> OpeningBalanceDate { get; set; }
        public string OpeningDrOrCrAcnt { get; set; }
        public Nullable<decimal> AmountDr { get; set; }
        public Nullable<decimal> AmountCr { get; set; }
        public Nullable<int> CompNo { get; set; }
        public Nullable<int> BranchNo { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> OBType { get; set; }
        public string SalesManId { get; set; }
        public Nullable<decimal> AmountDrBal { get; set; }
        public Nullable<decimal> AmountCrBal { get; set; }
        public Nullable<decimal> AmountCrCharged { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> Paid { get; set; }
        public Nullable<System.DateTime> ReceivalbleDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
        public Nullable<int> AgencyCheck { get; set; }
        public string GodownId { get; set; }
    }
}
