//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdjustmentSaleAcntDetail
    {
        public string AdjustmentID { get; set; }
        public int LineNo { get; set; }
        public string SinvoiceID { get; set; }
        public string OpeningBalanceID { get; set; }
        public string DebitNoteID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> SinvoiceDate { get; set; }
        public Nullable<decimal> InvRecBalance { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<int> ObCheckId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
    }
}
