//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdjustmentSaleAcnt
    {
        public string AdjustmentID { get; set; }
        public Nullable<int> AdjustmentNum { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public string Remarks { get; set; }
        public string CustomerID { get; set; }
        public string CustCrAcnt { get; set; }
        public string DrAcnt { get; set; }
        public Nullable<decimal> CrAmt { get; set; }
        public Nullable<decimal> DrAmt { get; set; }
        public string CustAccntNarration { get; set; }
        public string DrAcntNarration { get; set; }
        public Nullable<int> CompNo { get; set; }
        public Nullable<int> BranchNo { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
        public Nullable<int> Agency { get; set; }
        public string GodownId { get; set; }
    }
}
