//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvanceAgainstSalary
    {
        public string AdvAgainstSalID { get; set; }
        public Nullable<int> AdvAgainstSalNum { get; set; }
        public string EmpNo { get; set; }
        public Nullable<System.DateTime> AdvanceDate { get; set; }
        public Nullable<System.DateTime> AdvanceMonth { get; set; }
        public Nullable<decimal> GrossSalary { get; set; }
        public Nullable<decimal> AdvanceAmount { get; set; }
        public string AppAuth { get; set; }
        public string RecomAuth { get; set; }
        public Nullable<int> CompNo { get; set; }
        public Nullable<int> BranchNo { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
        public Nullable<decimal> BalanceSalary { get; set; }
    
        public virtual EmployeePersonalInfo EmployeePersonalInfo { get; set; }
    }
}
