//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvanceToPurchaserDetail
    {
        public string PurAdvanceID { get; set; }
        public int LineNo { get; set; }
        public decimal Amount { get; set; }
        public string ItemID { get; set; }
        public decimal BalanceAmount { get; set; }
        public Nullable<int> ItemClearedStatus { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
    }
}
