//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvanceAgainstBonu
    {
        public string AdvanceAgainstBonusId { get; set; }
        public int AdvanceAgainstBonusNum { get; set; }
        public string EmpNo { get; set; }
        public System.DateTime AdvanceDate { get; set; }
        public decimal AdvanceAmount { get; set; }
        public decimal BonusAmount { get; set; }
        public string AppAuth { get; set; }
        public string RecomAuth { get; set; }
        public int CompNo { get; set; }
        public int BranchNo { get; set; }
        public int LahTransferId { get; set; }
        public System.DateTime SaveDate { get; set; }
        public int DeletionID { get; set; }
        public System.DateTime BonusYear { get; set; }
        public string BonusId { get; set; }
        public decimal BalanceBonus { get; set; }
        public decimal AlreadyAdvanceTkn { get; set; }
    
        public virtual EmployeePersonalInfo EmployeePersonalInfo { get; set; }
    }
}
