//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgencyLeager
    {
        public System.DateTime SDate { get; set; }
        public string Dscr { get; set; }
        public string ChequeNo { get; set; }
        public decimal Dr { get; set; }
        public decimal Cr { get; set; }
        public System.DateTime fdate { get; set; }
        public System.DateTime tdate { get; set; }
        public int CompNo { get; set; }
        public int BranchNo { get; set; }
        public decimal OpBalance { get; set; }
        public decimal TotalBal { get; set; }
        public string Company_Name { get; set; }
        public string BranchName { get; set; }
        public string CustomerNo { get; set; }
        public string CustomerName { get; set; }
    }
}
