//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllSupplier
    {
        public string AllSupplierNo { get; set; }
        public string ContactNo { get; set; }
        public Nullable<int> STaxId { get; set; }
        public bool SupplierType { get; set; }
        public string AcntId { get; set; }
        public string RAcntId { get; set; }
        public int CompNo { get; set; }
        public int BranchNo { get; set; }
        public Nullable<int> SupplierNum { get; set; }
        public Nullable<int> Registerd { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
    }
}
