//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankChequeBookDetail
    {
        public string CheqBookId { get; set; }
        public decimal ChequeNumbers { get; set; }
        public int ChequeUsedStatus { get; set; }
        public int ChequeCancelStatus { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public Nullable<System.DateTime> UsedDate { get; set; }
        public int LineNum { get; set; }
        public decimal ChequeAmount { get; set; }
        public string UseDescription { get; set; }
        public int LahTransferId { get; set; }
        public int DeletionId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
    }
}
