//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bonu
    {
        public int BonId { get; set; }
        public string EmpId { get; set; }
        public Nullable<int> DesigId { get; set; }
        public Nullable<int> DeptId { get; set; }
        public Nullable<decimal> BonAmt { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> deldate { get; set; }
        public bool delstatus { get; set; }
        public Nullable<decimal> EmpTen { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public Nullable<System.DateTime> Tdate { get; set; }
        public Nullable<System.DateTime> BonDate { get; set; }
        public Nullable<int> cid { get; set; }
        public Nullable<int> CompNo { get; set; }
        public int BranchNo { get; set; }
        public int LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
    }
}
