//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BonusSetup
    {
        public string BonusID { get; set; }
        public Nullable<int> BonusNum { get; set; }
        public Nullable<System.DateTime> BonusDate { get; set; }
        public Nullable<System.DateTime> BonusYear { get; set; }
        public Nullable<decimal> BasicPayNo { get; set; }
        public Nullable<decimal> OtherAmt { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CompNo { get; set; }
        public Nullable<int> BranchNo { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
        public Nullable<int> BonusCal { get; set; }
    }
}
