//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public int Status { get; set; }
        public int CompNo { get; set; }
        public string Dscr { get; set; }
        public string AcntId { get; set; }
        public string BranchName { get; set; }
        public string BranchAddress { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public System.DateTime SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
    }
}
