//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColorOfChoice
    {
        public string ColorOfText { get; set; }
        public string ColorOfLabel { get; set; }
        public string ColorOfForm { get; set; }
        public string ColorOfCommandButton { get; set; }
        public string FontName { get; set; }
        public string ComboForeColors { get; set; }
        public string OptionAndCheckBox { get; set; }
        public string CheckBoxColor { get; set; }
        public string IconPictures { get; set; }
        public string ColorOfList { get; set; }
        public Nullable<int> PId { get; set; }
        public Nullable<int> CompNo { get; set; }
        public Nullable<int> BranchNo { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
    }
}
