//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Nullable<double> CompanyId { get; set; }
        public string CompDesc { get; set; }
        public bool companydelestatus { get; set; }
        public Nullable<System.DateTime> companydeledate { get; set; }
        public string Name { get; set; }
        public string ntn { get; set; }
        public string Address { get; set; }
        public string compntn { get; set; }
        public Nullable<double> LahTransferId { get; set; }
    }
}
