//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public string ContactNo { get; set; }
        public string Dscr { get; set; }
        public string SAddress { get; set; }
        public string PhoneNo { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string WebPage { get; set; }
        public string Email { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public string SaleTaxRegisterNo { get; set; }
        public string NationalIdNo { get; set; }
        public string NationalTaxNo { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<int> CompNo { get; set; }
        public int BranchNo { get; set; }
        public Nullable<int> ContactNum { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
    }
}
