//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostCenterNew
    {
        public string CostCenterId { get; set; }
        public string CostCenterName { get; set; }
        public int CostLevel { get; set; }
        public string SubCostCenterId1 { get; set; }
        public string SubCostCenterId2 { get; set; }
        public string SubCostCenterId3 { get; set; }
        public string SubCostCenterId4 { get; set; }
        public string SubCostCenterId5 { get; set; }
        public string SubCostCenterId6 { get; set; }
        public string SubCostCenterId7 { get; set; }
        public int CompNo { get; set; }
        public int BranchNo { get; set; }
        public int LahTransferId { get; set; }
        public System.DateTime SaveDate { get; set; }
        public int DeletionID { get; set; }
    }
}
