//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_Deals
    {
        public string DealID { get; set; }
        public decimal DealNo { get; set; }
        public bool DealType { get; set; }
        public string CustomerNo { get; set; }
        public string DealName { get; set; }
        public string DealStageID { get; set; }
        public string Priority { get; set; }
        public System.DateTime DealDate { get; set; }
        public System.DateTime DealCloseDate { get; set; }
        public string SalesManId { get; set; }
        public int CompNo { get; set; }
        public int BranchNo { get; set; }
        public int LahTransferId { get; set; }
        public System.DateTime SaveDate { get; set; }
        public int DeletionID { get; set; }
    }
}
