//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_SaleQuotation
    {
        public string QuoteId { get; set; }
        public decimal QuoteNo { get; set; }
        public string CustomerNo { get; set; }
        public string Remarks { get; set; }
        public System.DateTime QuoteDate { get; set; }
        public System.DateTime QuoteValidDate { get; set; }
        public string SalesManId { get; set; }
        public int CompNo { get; set; }
        public int BranchNo { get; set; }
        public int LahTransferId { get; set; }
        public System.DateTime SaveDate { get; set; }
        public int DeletionID { get; set; }
        public string RefDocId { get; set; }
        public string RefDocName { get; set; }
    }
}
