//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_Customers
    {
        public string CustomerNo { get; set; }
        public int CustNum { get; set; }
        public bool PotentialCustomer { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string ContactPerson { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public int CompNo { get; set; }
        public int BranchNo { get; set; }
        public int DeletionID { get; set; }
        public System.DateTime SaveDate { get; set; }
        public string CountryId { get; set; }
        public string CityId { get; set; }
        public string Email { get; set; }
        public string NationalTaxNo { get; set; }
        public string SaleTaxRegisterNo { get; set; }
        public string WebPage { get; set; }
    }
}
