//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDetail
    {
        public string CustomerNo { get; set; }
        public string ItemId { get; set; }
        public bool LahTransferId { get; set; }
        public bool DeletionID { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
    }
}
