//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deduction_of_tax
    {
        public string Name { get; set; }
        public string DesignDesc { get; set; }
        public Nullable<decimal> GS { get; set; }
        public Nullable<decimal> NetAmtTaxDed { get; set; }
        public Nullable<decimal> TaxForMonth { get; set; }
        public Nullable<System.DateTime> fdate { get; set; }
        public Nullable<System.DateTime> tdate { get; set; }
        public string CompDesc { get; set; }
        public Nullable<decimal> upto { get; set; }
        public string NTNNO { get; set; }
        public Nullable<System.DateTime> SalDate { get; set; }
        public int CompNo { get; set; }
        public int BranchNo { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
    }
}
