//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DelChallanDetail
    {
        public string DelChallanId { get; set; }
        public int LineNo { get; set; }
        public string ItemId { get; set; }
        public decimal DelQty { get; set; }
        public Nullable<decimal> IRate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> ItemClearStatus { get; set; }
        public Nullable<decimal> DelQtyBalance { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
        public decimal Packing { get; set; }
        public decimal Cartons { get; set; }
    }
}
