//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DelChallan
    {
        public string DelChallanId { get; set; }
        public string DelChallanNo { get; set; }
        public string CustomerNo { get; set; }
        public Nullable<System.DateTime> DelChallanDate { get; set; }
        public string Remarks { get; set; }
        public string DisOrdId { get; set; }
        public int CompNo { get; set; }
        public int BranchNo { get; set; }
        public string GateOutPutPass { get; set; }
        public string DriverName { get; set; }
        public string BiltyNo { get; set; }
        public string TrackNo { get; set; }
        public string TransortCo { get; set; }
        public string BatchNo { get; set; }
        public string SalesManId { get; set; }
        public Nullable<decimal> TotalQty { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public int GodownTransferId { get; set; }
        public string GodownId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
        public int DebitCheck { get; set; }
        public string PoNo { get; set; }
    }
}
