//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DelliveryChallanReportTable
    {
        public decimal DellRepId { get; set; }
        public Nullable<System.DateTime> DelliveryDate { get; set; }
        public string CustomerName { get; set; }
        public string Packing { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string ItemId { get; set; }
        public string ItemName { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string InvoiceID { get; set; }
        public string InvoiceNumber { get; set; }
        public string DelChallanId { get; set; }
        public Nullable<decimal> TotaQtyBags { get; set; }
        public string DelChallNumber { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
    }
}
