//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpDeduction
    {
        public string DetuctionId { get; set; }
        public int DetuctionNum { get; set; }
        public string EmpNo { get; set; }
        public System.DateTime DetuctionDate { get; set; }
        public System.DateTime DetuctionMonth { get; set; }
        public decimal IncomTax { get; set; }
        public decimal Fine { get; set; }
        public decimal Absenties { get; set; }
        public decimal AttendenceFine { get; set; }
        public decimal LoanInstalment { get; set; }
        public decimal AdvSalary { get; set; }
        public decimal Other { get; set; }
        public decimal TotalDeduct { get; set; }
        public decimal GrosSalary { get; set; }
        public decimal NetSalary { get; set; }
        public int CompNo { get; set; }
        public int BranchNo { get; set; }
        public int LahTransferId { get; set; }
        public System.DateTime SaveDate { get; set; }
        public int DeletionID { get; set; }
    }
}
