//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeOfficialInfo
    {
        public string EmpNo { get; set; }
        public string DesignId { get; set; }
        public string DeptID { get; set; }
        public string StatusID { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public string NTNNO { get; set; }
        public string PhExt { get; set; }
        public Nullable<int> CompID { get; set; }
        public string JobDesc { get; set; }
        public Nullable<int> RecomendAuth { get; set; }
        public Nullable<int> ApprovingAuth { get; set; }
        public string Eobino { get; set; }
        public string loc { get; set; }
        public Nullable<decimal> Sal { get; set; }
        public Nullable<int> Cid { get; set; }
        public string EmpType { get; set; }
        public string AccNo { get; set; }
        public Nullable<decimal> tax { get; set; }
        public Nullable<decimal> OldSal { get; set; }
        public string SS { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<int> CompNo { get; set; }
        public Nullable<int> BranchNo { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
    }
}
