//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmplyeePresAddress
    {
        public string EmpID { get; set; }
        public Nullable<int> CityId { get; set; }
        public string DistrictId { get; set; }
        public string Email { get; set; }
        public string MobNo { get; set; }
        public string PhNo { get; set; }
        public string Pradd { get; set; }
        public int LahTransferId { get; set; }
        public int CompNo { get; set; }
        public int BranchNo { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public int DeletionID { get; set; }
    }
}
