//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpPersonalInfo1
    {
        public string EmpNo { get; set; }
        public string Name { get; set; }
        public string Domicile { get; set; }
        public string FathName { get; set; }
        public string Religion { get; set; }
        public string Nationality { get; set; }
        public string NICNo { get; set; }
        public string BloodGrp { get; set; }
        public Nullable<System.DateTime> BrthDate { get; set; }
        public string EmerCont { get; set; }
        public string MaritStat { get; set; }
        public string EmerPhon { get; set; }
        public Nullable<int> ChildNo { get; set; }
        public string LatQual { get; set; }
        public string sex { get; set; }
        public string HelthIssu { get; set; }
        public string JobDesc { get; set; }
        public string CityDesc { get; set; }
        public string Pradd { get; set; }
        public string Pmadd { get; set; }
        public string Permcit { get; set; }
        public Nullable<decimal> Sal { get; set; }
        public string SpouseName { get; set; }
        public string PresMob { get; set; }
        public string PresPhno { get; set; }
        public string MobNo { get; set; }
        public string PhNo { get; set; }
        public string Permdist { get; set; }
        public string Presdist { get; set; }
        public string DeptDesc { get; set; }
        public string CompDesc { get; set; }
        public string DistDesc { get; set; }
        public Nullable<System.DateTime> SpouseDob { get; set; }
        public string StatDesc { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<int> CompNo { get; set; }
        public Nullable<int> BranchNo { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
    }
}
