//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SairaIndEntities : DbContext
    {
        public SairaIndEntities()
            : base("name=SairaIndEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountInfo> AccountInfoes { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<AccountsBackUp> AccountsBackUps { get; set; }
        public virtual DbSet<AccountsOpeningBalance> AccountsOpeningBalances { get; set; }
        public virtual DbSet<AdjustmentSaleAcnt> AdjustmentSaleAcnts { get; set; }
        public virtual DbSet<AdjustmentSaleAcntDetail> AdjustmentSaleAcntDetails { get; set; }
        public virtual DbSet<AdvanceAgainstBonu> AdvanceAgainstBonus { get; set; }
        public virtual DbSet<AdvanceToPurchaser> AdvanceToPurchasers { get; set; }
        public virtual DbSet<AdvanceToPurchaserDetail> AdvanceToPurchaserDetails { get; set; }
        public virtual DbSet<AllSupplier> AllSuppliers { get; set; }
        public virtual DbSet<BackupDataTransfer> BackupDataTransfers { get; set; }
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<BankChequeBook> BankChequeBooks { get; set; }
        public virtual DbSet<BankChequeCanelation> BankChequeCanelations { get; set; }
        public virtual DbSet<BonusSetup> BonusSetups { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Company1> Company1 { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<CostCenterNew> CostCenterNews { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<CRM_DealDetail> CRM_DealDetail { get; set; }
        public virtual DbSet<CRM_Deals> CRM_Deals { get; set; }
        public virtual DbSet<CRM_DealStage> CRM_DealStage { get; set; }
        public virtual DbSet<CRM_SaleQuotation> CRM_SaleQuotation { get; set; }
        public virtual DbSet<CRM_SaleQuotationDetail> CRM_SaleQuotationDetail { get; set; }
        public virtual DbSet<CustomerDetail> CustomerDetails { get; set; }
        public virtual DbSet<CustomerDtre> CustomerDtres { get; set; }
        public virtual DbSet<DebitNoteStax> DebitNoteStaxes { get; set; }
        public virtual DbSet<DebitNoteStaxDetail> DebitNoteStaxDetails { get; set; }
        public virtual DbSet<DelChallan> DelChallans { get; set; }
        public virtual DbSet<DelChallanDetail> DelChallanDetails { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Designation> Designations { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<dtproperty> dtproperties { get; set; }
        public virtual DbSet<EmpPersonalInfo1> EmpPersonalInfo1 { get; set; }
        public virtual DbSet<EmpStatu> EmpStatus { get; set; }
        public virtual DbSet<EOBISetup> EOBISetups { get; set; }
        public virtual DbSet<Expense> Expenses { get; set; }
        public virtual DbSet<ExpenseDetail> ExpenseDetails { get; set; }
        public virtual DbSet<FGOpeningBalance> FGOpeningBalances { get; set; }
        public virtual DbSet<FGRecieptNote> FGRecieptNotes { get; set; }
        public virtual DbSet<FGRecieptNoteDetail> FGRecieptNoteDetails { get; set; }
        public virtual DbSet<Fgreturn> Fgreturns { get; set; }
        public virtual DbSet<FgReturnDetail> FgReturnDetails { get; set; }
        public virtual DbSet<FinishedGood> FinishedGoods { get; set; }
        public virtual DbSet<FinYear> FinYears { get; set; }
        public virtual DbSet<FontsTable> FontsTables { get; set; }
        public virtual DbSet<GodownType> GodownTypes { get; set; }
        public virtual DbSet<GRN> GRNs { get; set; }
        public virtual DbSet<GroupChange> GroupChanges { get; set; }
        public virtual DbSet<Holiday> Holidays { get; set; }
        public virtual DbSet<IncDetail> IncDetails { get; set; }
        public virtual DbSet<Increment> Increments { get; set; }
        public virtual DbSet<Invoice_detail> Invoice_detail { get; set; }
        public virtual DbSet<Invoice_Info> Invoice_Info { get; set; }
        public virtual DbSet<InvoicePrintingCount> InvoicePrintingCounts { get; set; }
        public virtual DbSet<InvoiceReceipt> InvoiceReceipts { get; set; }
        public virtual DbSet<InvoiceReceiptDetail> InvoiceReceiptDetails { get; set; }
        public virtual DbSet<InvoiceTerm> InvoiceTerms { get; set; }
        public virtual DbSet<InvPayment> InvPayments { get; set; }
        public virtual DbSet<InvPaymentDetail> InvPaymentDetails { get; set; }
        public virtual DbSet<ItemsStock> ItemsStocks { get; set; }
        public virtual DbSet<JournalDetail> JournalDetails { get; set; }
        public virtual DbSet<JournalDetail2> JournalDetail2 { get; set; }
        public virtual DbSet<Journal> Journals { get; set; }
        public virtual DbSet<Journals2> Journals2 { get; set; }
        public virtual DbSet<LCBond> LCBonds { get; set; }
        public virtual DbSet<LeaveEntitlement> LeaveEntitlements { get; set; }
        public virtual DbSet<LoanAdjuststment> LoanAdjuststments { get; set; }
        public virtual DbSet<LoanTaken> LoanTakens { get; set; }
        public virtual DbSet<LocalPurchaseInvDetail> LocalPurchaseInvDetails { get; set; }
        public virtual DbSet<LocalPurchaseInvoice> LocalPurchaseInvoices { get; set; }
        public virtual DbSet<LocalSupplier> LocalSuppliers { get; set; }
        public virtual DbSet<OtherPurchaseInvDetail> OtherPurchaseInvDetails { get; set; }
        public virtual DbSet<OtherPurchaseInvoice> OtherPurchaseInvoices { get; set; }
        public virtual DbSet<Party> Parties { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PaymentDetail> PaymentDetails { get; set; }
        public virtual DbSet<PaymentType> PaymentTypes { get; set; }
        public virtual DbSet<PReturn> PReturns { get; set; }
        public virtual DbSet<PReturnDetail> PReturnDetails { get; set; }
        public virtual DbSet<PriceList> PriceLists { get; set; }
        public virtual DbSet<PurAdvance> PurAdvances { get; set; }
        public virtual DbSet<PurchaseRequest> PurchaseRequests { get; set; }
        public virtual DbSet<PurchaseRequestDetail> PurchaseRequestDetails { get; set; }
        public virtual DbSet<PurchaseRequisitionOrderDetail> PurchaseRequisitionOrderDetails { get; set; }
        public virtual DbSet<PurDeliveryChallDetail> PurDeliveryChallDetails { get; set; }
        public virtual DbSet<PurDellChallanMaster> PurDellChallanMasters { get; set; }
        public virtual DbSet<RawMaterial> RawMaterials { get; set; }
        public virtual DbSet<ReceiptBounce> ReceiptBounces { get; set; }
        public virtual DbSet<ReceiptsCommission> ReceiptsCommissions { get; set; }
        public virtual DbSet<Recieved> Recieveds { get; set; }
        public virtual DbSet<RecievedDetail> RecievedDetails { get; set; }
        public virtual DbSet<RmGrn> RmGrns { get; set; }
        public virtual DbSet<RmGrnDetail> RmGrnDetails { get; set; }
        public virtual DbSet<RmGrnReturnP> RmGrnReturnPs { get; set; }
        public virtual DbSet<RmGrnReturnPDetail> RmGrnReturnPDetails { get; set; }
        public virtual DbSet<RMreturnp> RMreturnps { get; set; }
        public virtual DbSet<RmReturnPDetail> RmReturnPDetails { get; set; }
        public virtual DbSet<Salary> Salaries { get; set; }
        public virtual DbSet<SalaryDetail> SalaryDetails { get; set; }
        public virtual DbSet<SalaryMaster> SalaryMasters { get; set; }
        public virtual DbSet<SalarySetup> SalarySetups { get; set; }
        public virtual DbSet<SaleAdvance> SaleAdvances { get; set; }
        public virtual DbSet<SaleAdvanceAdjustment> SaleAdvanceAdjustments { get; set; }
        public virtual DbSet<SaleAdvanceAdjustmentDetail> SaleAdvanceAdjustmentDetails { get; set; }
        public virtual DbSet<SaleAgingReport> SaleAgingReports { get; set; }
        public virtual DbSet<SaleAgingTest> SaleAgingTests { get; set; }
        public virtual DbSet<SaleDebitNote> SaleDebitNotes { get; set; }
        public virtual DbSet<SaleInvoice> SaleInvoices { get; set; }
        public virtual DbSet<SaleInvoiceDetail> SaleInvoiceDetails { get; set; }
        public virtual DbSet<SaleInvoiceWeb> SaleInvoiceWebs { get; set; }
        public virtual DbSet<SalesCommReport> SalesCommReports { get; set; }
        public virtual DbSet<SalesMan> SalesMen { get; set; }
        public virtual DbSet<SaleTax> SaleTaxes { get; set; }
        public virtual DbSet<SaleTaxSumup> SaleTaxSumups { get; set; }
        public virtual DbSet<tblItemStockOpeningBalance> tblItemStockOpeningBalances { get; set; }
        public virtual DbSet<Title> Titles { get; set; }
        public virtual DbSet<ToolsAndSpare> ToolsAndSpares { get; set; }
        public virtual DbSet<Type> Types { get; set; }
        public virtual DbSet<VoucherType> VoucherTypes { get; set; }
        public virtual DbSet<Account_Head_New> Account_Head_New { get; set; }
        public virtual DbSet<Advancesalpara> Advancesalparas { get; set; }
        public virtual DbSet<AgencyLeager> AgencyLeagers { get; set; }
        public virtual DbSet<AllPara> AllParas { get; set; }
        public virtual DbSet<AllRepPara> AllRepParas { get; set; }
        public virtual DbSet<Attendence> Attendences { get; set; }
        public virtual DbSet<AttendRep> AttendReps { get; set; }
        public virtual DbSet<BankChequeBookDetail> BankChequeBookDetails { get; set; }
        public virtual DbSet<BankPaymentBookSummary> BankPaymentBookSummaries { get; set; }
        public virtual DbSet<Bonu> Bonus { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<Carlease> Carleases { get; set; }
        public virtual DbSet<Carleasedetail> Carleasedetails { get; set; }
        public virtual DbSet<CashPaymentBook> CashPaymentBooks { get; set; }
        public virtual DbSet<Catagory> Catagories { get; set; }
        public virtual DbSet<ColorOfChoice> ColorOfChoices { get; set; }
        public virtual DbSet<ColorOfChoice2> ColorOfChoice2 { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<ControlAcnt> ControlAcnts { get; set; }
        public virtual DbSet<CorrBank> CorrBanks { get; set; }
        public virtual DbSet<Country1> Country1 { get; set; }
        public virtual DbSet<CustomerDtreDetail> CustomerDtreDetails { get; set; }
        public virtual DbSet<Deduction_of_tax> Deduction_of_tax { get; set; }
        public virtual DbSet<DelliveryChallanReportTable> DelliveryChallanReportTables { get; set; }
        public virtual DbSet<DeptChangeRep> DeptChangeReps { get; set; }
        public virtual DbSet<EmpDeduction> EmpDeductions { get; set; }
        public virtual DbSet<EmployeeOfficialInfo> EmployeeOfficialInfoes { get; set; }
        public virtual DbSet<EmployeePermAddress> EmployeePermAddresses { get; set; }
        public virtual DbSet<EmplyeePresAddress> EmplyeePresAddresses { get; set; }
        public virtual DbSet<EmpSalary> EmpSalaries { get; set; }
        public virtual DbSet<EOBIDetail> EOBIDetails { get; set; }
        public virtual DbSet<ExpenseInv> ExpenseInvs { get; set; }
        public virtual DbSet<ExpenseInvDetail> ExpenseInvDetails { get; set; }
        public virtual DbSet<ExpenseTitle> ExpenseTitles { get; set; }
        public virtual DbSet<Fine> Fines { get; set; }
        public virtual DbSet<FinYearPDetail> FinYearPDetails { get; set; }
        public virtual DbSet<ForeignSupplier> ForeignSuppliers { get; set; }
        public virtual DbSet<Group1> Group1 { get; set; }
        public virtual DbSet<GroupAssign> GroupAssigns { get; set; }
        public virtual DbSet<Halfday> Halfdays { get; set; }
        public virtual DbSet<ImpGLInt> ImpGLInts { get; set; }
        public virtual DbSet<InsurancePolicy> InsurancePolicies { get; set; }
        public virtual DbSet<ItemFinishGoodRegister> ItemFinishGoodRegisters { get; set; }
        public virtual DbSet<ItemRawMaterialRegister> ItemRawMaterialRegisters { get; set; }
        public virtual DbSet<ItemTransferToGodown> ItemTransferToGodowns { get; set; }
        public virtual DbSet<LcCont> LcConts { get; set; }
        public virtual DbSet<LcContDetail> LcContDetails { get; set; }
        public virtual DbSet<lcContract> lcContracts { get; set; }
        public virtual DbSet<LCExBond> LCExBonds { get; set; }
        public virtual DbSet<LCExBondDetail> LCExBondDetails { get; set; }
        public virtual DbSet<LCInBond> LCInBonds { get; set; }
        public virtual DbSet<LCType> LCTypes { get; set; }
        public virtual DbSet<LeaveApplication> LeaveApplications { get; set; }
        public virtual DbSet<LeaveBal> LeaveBals { get; set; }
        public virtual DbSet<LeaveType> LeaveTypes { get; set; }
        public virtual DbSet<Loan> Loans { get; set; }
        public virtual DbSet<LoanAdjust> LoanAdjusts { get; set; }
        public virtual DbSet<LoanTransDetail> LoanTransDetails { get; set; }
        public virtual DbSet<LogHistory> LogHistories { get; set; }
        public virtual DbSet<MainAcnt> MainAcnts { get; set; }
        public virtual DbSet<Medical> Medicals { get; set; }
        public virtual DbSet<MedicalEntitlement> MedicalEntitlements { get; set; }
        public virtual DbSet<MedicalTran> MedicalTrans { get; set; }
        public virtual DbSet<MedRec> MedRecs { get; set; }
        public virtual DbSet<Next> Nexts { get; set; }
        public virtual DbSet<Oiltype> Oiltypes { get; set; }
        public virtual DbSet<OverTime> OverTimes { get; set; }
        public virtual DbSet<Owner> Owners { get; set; }
        public virtual DbSet<Password> Passwords { get; set; }
        public virtual DbSet<Pendingdayavail> Pendingdayavails { get; set; }
        public virtual DbSet<pendingdayoff> pendingdayoffs { get; set; }
        public virtual DbSet<Petrolcredit> Petrolcredits { get; set; }
        public virtual DbSet<Promotion> Promotions { get; set; }
        public virtual DbSet<prompara> promparas { get; set; }
        public virtual DbSet<PurchaseAgingTest> PurchaseAgingTests { get; set; }
        public virtual DbSet<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual DbSet<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
        public virtual DbSet<ReceiptBookSummary> ReceiptBookSummaries { get; set; }
        public virtual DbSet<ReductionTax> ReductionTaxes { get; set; }
        public virtual DbSet<Resign> Resigns { get; set; }
        public virtual DbSet<RestDay> RestDays { get; set; }
        public virtual DbSet<RestDayHistory> RestDayHistories { get; set; }
        public virtual DbSet<RMIssueP> RMIssuePs { get; set; }
        public virtual DbSet<RMIssuePdetail> RMIssuePdetails { get; set; }
        public virtual DbSet<RMItemTransferToUnit> RMItemTransferToUnits { get; set; }
        public virtual DbSet<RMItemTransferToUnitMaster> RMItemTransferToUnitMasters { get; set; }
        public virtual DbSet<SalCalc> SalCalcs { get; set; }
        public virtual DbSet<SaleTaxDetail> SaleTaxDetails { get; set; }
        public virtual DbSet<SControlAcnt> SControlAcnts { get; set; }
        public virtual DbSet<SMainAcnt> SMainAcnts { get; set; }
        public virtual DbSet<SReturn> SReturns { get; set; }
        public virtual DbSet<SReturnDetail> SReturnDetails { get; set; }
        public virtual DbSet<TaxIdentity> TaxIdentities { get; set; }
        public virtual DbSet<TaxRate> TaxRates { get; set; }
        public virtual DbSet<tblGLAssetAccount> tblGLAssetAccounts { get; set; }
        public virtual DbSet<tblGLBalanceSheetAccount> tblGLBalanceSheetAccounts { get; set; }
        public virtual DbSet<tblGLBalanceSheetAccountSum> tblGLBalanceSheetAccountSums { get; set; }
        public virtual DbSet<tblGLProfitLossAccount> tblGLProfitLossAccounts { get; set; }
        public virtual DbSet<tblGLProfitLossAccountSum> tblGLProfitLossAccountSums { get; set; }
        public virtual DbSet<tblStoreUnit> tblStoreUnits { get; set; }
        public virtual DbSet<tblSupplierBuyer> tblSupplierBuyers { get; set; }
        public virtual DbSet<TempAtt> TempAtts { get; set; }
        public virtual DbSet<Test> Tests { get; set; }
        public virtual DbSet<TimeReport> TimeReports { get; set; }
        public virtual DbSet<Transfer> Transfers { get; set; }
        public virtual DbSet<UserRight> UserRights { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Visite> Visites { get; set; }
        public virtual DbSet<SalesOrder> SalesOrders { get; set; }
        public virtual DbSet<SalesOrderDetail> SalesOrderDetails { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CRM_Customers> CRM_Customers { get; set; }
        public virtual DbSet<Purchaser> Purchasers { get; set; }
        public virtual DbSet<AdvanceAgainstSalary> AdvanceAgainstSalaries { get; set; }
        public virtual DbSet<BonusCalculation> BonusCalculations { get; set; }
        public virtual DbSet<EmployeePersonalInfo> EmployeePersonalInfoes { get; set; }
        public virtual DbSet<IncomeTaxSetup> IncomeTaxSetups { get; set; }
        public virtual DbSet<IncomeTaxDetail> IncomeTaxDetails { get; set; }
        public virtual DbSet<PurchaseRequisitionOrder> PurchaseRequisitionOrders { get; set; }
    
        public virtual int Sp_CurrentStock(string itemid, string compNo, string branchNo, string storeUnitId, string godownId, string toDate)
        {
            var itemidParameter = itemid != null ?
                new ObjectParameter("Itemid", itemid) :
                new ObjectParameter("Itemid", typeof(string));
    
            var compNoParameter = compNo != null ?
                new ObjectParameter("CompNo", compNo) :
                new ObjectParameter("CompNo", typeof(string));
    
            var branchNoParameter = branchNo != null ?
                new ObjectParameter("BranchNo", branchNo) :
                new ObjectParameter("BranchNo", typeof(string));
    
            var storeUnitIdParameter = storeUnitId != null ?
                new ObjectParameter("StoreUnitId", storeUnitId) :
                new ObjectParameter("StoreUnitId", typeof(string));
    
            var godownIdParameter = godownId != null ?
                new ObjectParameter("GodownId", godownId) :
                new ObjectParameter("GodownId", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("toDate", toDate) :
                new ObjectParameter("toDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_CurrentStock", itemidParameter, compNoParameter, branchNoParameter, storeUnitIdParameter, godownIdParameter, toDateParameter);
        }
    }
}
