//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense
    {
        public string ExpenseId { get; set; }
        public string ExpenseNo { get; set; }
        public Nullable<int> ShipDocId { get; set; }
        public string VoucherTypeId { get; set; }
        public string ChqNo { get; set; }
        public string ChqDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Tamt { get; set; }
        public Nullable<int> LcContId { get; set; }
        public Nullable<int> BankNo { get; set; }
        public Nullable<int> VoucherNo { get; set; }
        public Nullable<System.DateTime> VoucherDate { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> ExchRate { get; set; }
        public Nullable<decimal> AdjustMargin { get; set; }
        public string PayType { get; set; }
        public string TransBank { get; set; }
        public int CompNo { get; set; }
        public int BranchNo { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
    }
}
