//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseInv
    {
        public string ExpInvId { get; set; }
        public int ExpInvNum { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> SysDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CompNo { get; set; }
        public int BranchNo { get; set; }
        public int LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
    }
}
