//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FGOpeningBalance
    {
        public string OpeningId { get; set; }
        public string ItemID { get; set; }
        public System.DateTime OpeningDate { get; set; }
        public string TransactionId { get; set; }
        public decimal OpeningQty { get; set; }
        public decimal CurrentQty { get; set; }
        public int CompNo { get; set; }
        public int BranchNo { get; set; }
        public string GodownID { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
        public Nullable<decimal> OpeningNum { get; set; }
    }
}
