//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FGRecieptNote
    {
        public string FGRId { get; set; }
        public string FGRNo { get; set; }
        public Nullable<System.DateTime> FGRDate { get; set; }
        public string BatchNo { get; set; }
        public string Remarks { get; set; }
        public int CompNo { get; set; }
        public int BranchNo { get; set; }
        public string GodownID { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
    }
}
