//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fine
    {
        public string FineId { get; set; }
        public Nullable<int> FineNum { get; set; }
        public string deptid { get; set; }
        public string desigid { get; set; }
        public string empid { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<decimal> fineAmount { get; set; }
        public Nullable<int> cid { get; set; }
        public string Fdesc { get; set; }
        public Nullable<int> CompNo { get; set; }
        public Nullable<int> BranchNo { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
    }
}
