//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GodownType
    {
        public string GodownId { get; set; }
        public string GodownName { get; set; }
        public int CompNo { get; set; }
        public int BranchNo { get; set; }
        public Nullable<int> GodownNum { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public string GodownAbbre { get; set; }
        public Nullable<int> AgencyType { get; set; }
        public string AgencyAcntID { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
        public int ItemStore { get; set; }
    }
}
