//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImpGLInt
    {
        public string BillPayAble { get; set; }
        public string CashAcc { get; set; }
        public string ImportPurchases { get; set; }
        public string SaleTaxAcc { get; set; }
        public string InComeTaxAcc { get; set; }
        public string OutPayAcc { get; set; }
        public string ddaacc { get; set; }
        public int SNo { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
    }
}
