//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceReceiptDetail
    {
        public string IrId { get; set; }
        public int lineno { get; set; }
        public string SInvoiceID { get; set; }
        public string OpeningBalanceID { get; set; }
        public string DebitNoteID { get; set; }
        public string DebitNoteSTaxID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> SInvoiceDate { get; set; }
        public Nullable<decimal> InvRecBalance { get; set; }
        public Nullable<int> GetAmtStatus { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<int> ObCheckId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
    
        public virtual InvoiceReceipt InvoiceReceipt { get; set; }
    }
}
