//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_detail
    {
        public string Invoice_No { get; set; }
        public string buyer_regno { get; set; }
        public string buyer_name { get; set; }
        public string seller_RegNo { get; set; }
        public System.DateTime invoice_date { get; set; }
        public int S_no { get; set; }
        public string invoice_status { get; set; }
        public string Tax_period { get; set; }
        public string pct_code { get; set; }
        public string Pct_desc { get; set; }
        public decimal Quantity { get; set; }
        public string UOM { get; set; }
        public decimal Excluded_SalTax { get; set; }
        public decimal Included_SaleTax { get; set; }
        public decimal SalTax { get; set; }
        public string SRO_status { get; set; }
        public decimal SRO_Serial { get; set; }
    }
}
