//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoicePrintingCount
    {
        public int InvoicePrintID { get; set; }
        public string SaleInvId { get; set; }
        public Nullable<int> PrintNo { get; set; }
        public Nullable<int> PId { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> PrintDate { get; set; }
        public Nullable<int> CompNo { get; set; }
        public Nullable<int> BranchNo { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
    }
}
