//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_Info
    {
        public string Invoice_No { get; set; }
        public System.DateTime Invoice_date { get; set; }
        public string Tax_period { get; set; }
        public string Seller_RegNo { get; set; }
        public string Invoice_status { get; set; }
        public string seller_name { get; set; }
        public string seller_address { get; set; }
        public string buyer_regno { get; set; }
        public string buyer_name { get; set; }
        public string buyer_address { get; set; }
        public int S_No { get; set; }
        public decimal TotalSalesTax { get; set; }
        public decimal TotalExcludSalTax { get; set; }
    }
}
