//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceReceipt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvoiceReceipt()
        {
            this.InvoiceReceiptDetails = new HashSet<InvoiceReceiptDetail>();
        }
    
        public string IrID { get; set; }
        public Nullable<int> IrNO { get; set; }
        public Nullable<System.DateTime> IrDate { get; set; }
        public string CustomerID { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public Nullable<int> CompNo { get; set; }
        public Nullable<int> BranchNo { get; set; }
        public string PaymentFromBank { get; set; }
        public string ChequeNo { get; set; }
        public string AcntId { get; set; }
        public int GetId { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
        public Nullable<int> GodownDiff { get; set; }
        public Nullable<int> Bouce { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceReceiptDetail> InvoiceReceiptDetails { get; set; }
    }
}
