//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalDetail
    {
        public string JournalId { get; set; }
        public int LineNo { get; set; }
        public string AcntId { get; set; }
        public string Dscr { get; set; }
        public decimal Dr { get; set; }
        public decimal Cr { get; set; }
        public string ChequeNo { get; set; }
        public decimal Balance { get; set; }
        public Nullable<decimal> BalType { get; set; }
        public Nullable<int> AccountTypeID { get; set; }
        public int LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public int DeletionID { get; set; }
    }
}
