//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        public string JournalId { get; set; }
        public string VoucherTypeId { get; set; }
        public decimal VoucherNo { get; set; }
        public System.DateTime TranDate { get; set; }
        public string Remarks { get; set; }
        public int Status { get; set; }
        public int CompNo { get; set; }
        public int Posted { get; set; }
        public int LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public int DeletionID { get; set; }
        public decimal JournalNum { get; set; }
        public int Id { get; set; }
    }
}
