//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCExBond
    {
        public decimal LCExBondId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> VoucherNo { get; set; }
        public string VoucherTypeId { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> LCContId { get; set; }
        public Nullable<decimal> ShipDocId { get; set; }
        public string ChqNo { get; set; }
        public Nullable<System.DateTime> ChqDate { get; set; }
        public Nullable<System.DateTime> VoucherDate { get; set; }
        public Nullable<decimal> TAmt { get; set; }
        public Nullable<int> BankNo { get; set; }
        public Nullable<int> Bonded { get; set; }
        public string Bond { get; set; }
        public int CompNo { get; set; }
        public int BranchNo { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
    }
}
