//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCInBond
    {
        public int LCInBondID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> VoucherNo { get; set; }
        public string VoucherTypeID { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> LCContID { get; set; }
        public Nullable<decimal> ShipDocID { get; set; }
        public string ChqNo { get; set; }
        public Nullable<System.DateTime> ChqDate { get; set; }
        public Nullable<System.DateTime> VoucherDate { get; set; }
        public Nullable<decimal> Tamt { get; set; }
        public Nullable<int> BankNo { get; set; }
        public Nullable<int> Bond { get; set; }
        public string BillNo { get; set; }
        public int CompNo { get; set; }
        public int BranchNo { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
    }
}
