//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanAdjuststment
    {
        public string LoanAdjId { get; set; }
        public Nullable<int> LoanAdjNum { get; set; }
        public string EmpNo { get; set; }
        public string LoanTakenId { get; set; }
        public Nullable<decimal> LoanAmt { get; set; }
        public Nullable<System.DateTime> AdjDate { get; set; }
        public Nullable<decimal> OldInstallAmt { get; set; }
        public Nullable<decimal> NewInsallAmt { get; set; }
        public Nullable<int> InstallNo { get; set; }
        public Nullable<int> AddInstallNo { get; set; }
        public Nullable<int> RemainInstall { get; set; }
        public Nullable<decimal> LoanReceived { get; set; }
        public Nullable<decimal> AdjustmentAmount { get; set; }
        public string AppAuth { get; set; }
        public string RecomAuth { get; set; }
        public Nullable<int> CompNo { get; set; }
        public Nullable<int> BranchNo { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
    
        public virtual LoanTaken LoanTaken { get; set; }
        public virtual EmployeePersonalInfo EmployeePersonalInfo { get; set; }
    }
}
