//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanTransDetail
    {
        public decimal Id { get; set; }
        public string EmpId { get; set; }
        public Nullable<int> InstallNo { get; set; }
        public Nullable<decimal> InstallAmt { get; set; }
        public Nullable<System.DateTime> InstallDate { get; set; }
        public Nullable<int> DeptId { get; set; }
        public Nullable<int> DesigId { get; set; }
        public Nullable<int> CompId { get; set; }
        public Nullable<int> RemainingInstallment { get; set; }
        public Nullable<decimal> LoanReceived { get; set; }
        public Nullable<decimal> LoanAmt { get; set; }
        public Nullable<decimal> Adjustment { get; set; }
        public Nullable<decimal> PrevInst { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
    }
}
