//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalPurchaseInvDetail
    {
        public string PInvoiceId { get; set; }
        public int LineNo { get; set; }
        public string ItemId { get; set; }
        public Nullable<decimal> PQty { get; set; }
        public string TaxIdentityId { get; set; }
        public decimal PRate { get; set; }
        public Nullable<decimal> TPrice { get; set; }
        public Nullable<decimal> AmtWoSt { get; set; }
        public Nullable<decimal> STaxPayAble { get; set; }
        public Nullable<int> STaxCalFlag { get; set; }
        public Nullable<decimal> SaleTax { get; set; }
        public Nullable<decimal> AmtWSt { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<System.DateTime> ItemDueDate { get; set; }
        public Nullable<decimal> SaleTaxRate { get; set; }
        public Nullable<decimal> ASaleTaxRate { get; set; }
        public Nullable<int> ItemClearStatus { get; set; }
        public Nullable<decimal> InvQtyBalance { get; set; }
        public string BillNo { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
        public string OrderType { get; set; }
        public string OrderId { get; set; }
        public string SupplierAcnt { get; set; }
        public Nullable<decimal> BAmount { get; set; }
        public Nullable<decimal> PAmount { get; set; }
        public Nullable<int> Paid { get; set; }
    }
}
