//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogHistory
    {
        public decimal LogId { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> LDate { get; set; }
        public Nullable<decimal> PrevAmt { get; set; }
        public decimal CurrAmt { get; set; }
        public string Remarks { get; set; }
        public string VourType { get; set; }
        public string VourNo { get; set; }
        public string ModStatus { get; set; }
        public string CompNo { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> VoucherDate { get; set; }
        public string JournalId { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
    }
}
