//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalEntitlement
    {
        public int medentid { get; set; }
        public Nullable<int> deptid { get; set; }
        public string empid { get; set; }
        public Nullable<int> desigid { get; set; }
        public Nullable<int> medidescid { get; set; }
        public Nullable<decimal> mediamt { get; set; }
        public bool delstatus { get; set; }
        public Nullable<System.DateTime> deldate { get; set; }
        public Nullable<System.DateTime> entitledate { get; set; }
        public Nullable<int> cid { get; set; }
        public Nullable<System.DateTime> Tdate { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
    }
}
