//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedRec
    {
        public decimal medrecid { get; set; }
        public string empid { get; set; }
        public Nullable<System.DateTime> Tdate { get; set; }
        public Nullable<int> deptid { get; set; }
        public Nullable<int> desigid { get; set; }
        public Nullable<int> cid { get; set; }
        public Nullable<decimal> amtused { get; set; }
        public Nullable<int> medid { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
    }
}
