//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Next
    {
        public Nullable<int> TransactionId { get; set; }
        public Nullable<int> JournalId { get; set; }
        public Nullable<int> FinYearId { get; set; }
        public Nullable<int> VourcherTypeId { get; set; }
        public int PID { get; set; }
        public string Status { get; set; }
        public Nullable<int> LogId { get; set; }
        public Nullable<int> porderid { get; set; }
        public Nullable<int> Allsupplierno { get; set; }
        public Nullable<int> Contactno { get; set; }
        public Nullable<int> localsupplierno { get; set; }
        public Nullable<int> fsupplierno { get; set; }
        public Nullable<int> Brandid { get; set; }
        public Nullable<int> Catagoryid { get; set; }
        public Nullable<int> Typeid { get; set; }
        public Nullable<int> PInvoiceId { get; set; }
        public Nullable<int> customerId { get; set; }
        public Nullable<int> Saleordid { get; set; }
        public Nullable<int> prequestid { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> FGId { get; set; }
        public Nullable<int> RMId { get; set; }
        public Nullable<int> TSId { get; set; }
        public Nullable<int> paymentid { get; set; }
        public Nullable<int> puradvid { get; set; }
        public Nullable<int> FGRId { get; set; }
        public Nullable<int> purchaserid { get; set; }
        public Nullable<int> invpayid { get; set; }
        public Nullable<int> PReturnId { get; set; }
        public Nullable<int> SalesManId { get; set; }
        public Nullable<int> pricelist { get; set; }
        public Nullable<int> SaleTaxId { get; set; }
        public Nullable<int> SaleAdvanceId { get; set; }
        public Nullable<int> doid { get; set; }
        public Nullable<int> BankId { get; set; }
        public Nullable<int> saleinvId { get; set; }
        public Nullable<int> irid { get; set; }
        public Nullable<int> SreturnId { get; set; }
        public Nullable<int> GRNID { get; set; }
        public Nullable<int> issueid { get; set; }
        public Nullable<int> issuereturnid { get; set; }
        public Nullable<int> fgreturnid { get; set; }
        public Nullable<int> lctypeid { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> CurrencyNo { get; set; }
        public Nullable<int> exptitleid { get; set; }
        public Nullable<int> DelChallanId { get; set; }
        public Nullable<int> CorrBankID { get; set; }
    }
}
