//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherPurchaseInvDetail
    {
        public string OPInvoiceId { get; set; }
        public int LineNo { get; set; }
        public string SupplierAcntID { get; set; }
        public string ItemAccount { get; set; }
        public Nullable<decimal> SaleTax { get; set; }
        public Nullable<decimal> AmtWoSt { get; set; }
        public Nullable<decimal> PQTY { get; set; }
        public Nullable<decimal> PRate { get; set; }
        public Nullable<decimal> AmtWSt { get; set; }
        public Nullable<System.DateTime> ItemDueDate { get; set; }
        public string Narration { get; set; }
        public Nullable<decimal> SaleTaxRate { get; set; }
        public Nullable<decimal> ItemClearStatus { get; set; }
        public Nullable<decimal> InvQtyBalance { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DueDays { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<int> Taxidentityid { get; set; }
        public Nullable<int> DeletionID { get; set; }
    }
}
