//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherPurchaseInvoice
    {
        public string OPInvoiceId { get; set; }
        public string OPInvoiceNo { get; set; }
        public Nullable<System.DateTime> PDate { get; set; }
        public Nullable<decimal> TAmount { get; set; }
        public string BillNo { get; set; }
        public string SupplierAcntID { get; set; }
        public Nullable<decimal> SaleTax { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> PaymentTypeid { get; set; }
        public Nullable<int> CompNo { get; set; }
        public Nullable<int> BranchNo { get; set; }
        public Nullable<int> Paid { get; set; }
        public Nullable<decimal> PAmount { get; set; }
        public Nullable<decimal> BAmount { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
    }
}
