//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Password
    {
        public int PId { get; set; }
        public string UserPass { get; set; }
        public string ConPass { get; set; }
        public string UserName { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<int> CompNo { get; set; }
        public Nullable<int> BranchNo { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
        public Nullable<int> RightAdd { get; set; }
        public Nullable<int> RightEdit { get; set; }
        public Nullable<int> RightDelete { get; set; }
        public string ApprovedStatus { get; set; }
    }
}
