//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Petrolcredit
    {
        public int petrolcreditid { get; set; }
        public string empid { get; set; }
        public Nullable<decimal> petroldescid { get; set; }
        public Nullable<decimal> Petrolamt { get; set; }
        public bool delstatus { get; set; }
        public Nullable<System.DateTime> deldate { get; set; }
        public Nullable<int> deptid { get; set; }
        public Nullable<int> desigid { get; set; }
        public Nullable<System.DateTime> creditdate { get; set; }
        public Nullable<int> cid { get; set; }
        public Nullable<decimal> Amt { get; set; }
        public string Slip { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
    }
}
