//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PReturnDetail
    {
        public string PReturnId { get; set; }
        public int LineNo { get; set; }
        public string ItemId { get; set; }
        public Nullable<int> RQty { get; set; }
        public Nullable<decimal> RRate { get; set; }
        public Nullable<decimal> AmtWost { get; set; }
        public Nullable<decimal> AmtStax { get; set; }
        public Nullable<decimal> Amtwst { get; set; }
        public string ItemNarration { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
        public string OrderType { get; set; }
        public string OrderID { get; set; }
        public string SupOrPurID { get; set; }
    }
}
