//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceList
    {
        public string PLid { get; set; }
        public string customerid { get; set; }
        public string itemid { get; set; }
        public Nullable<decimal> price1 { get; set; }
        public Nullable<decimal> price2 { get; set; }
        public Nullable<decimal> price3 { get; set; }
        public Nullable<decimal> price4 { get; set; }
        public Nullable<decimal> price5 { get; set; }
        public int CompNo { get; set; }
        public int BranchNo { get; set; }
        public Nullable<int> PriceListNum { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
    }
}
