//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion
    {
        public int PromId { get; set; }
        public string EmpId { get; set; }
        public Nullable<int> PresDesigId { get; set; }
        public Nullable<int> NewDesigId { get; set; }
        public Nullable<int> DeptId { get; set; }
        public Nullable<System.DateTime> PromDate { get; set; }
        public Nullable<decimal> CurrSal { get; set; }
        public Nullable<decimal> CurrHouseRnt { get; set; }
        public Nullable<decimal> CurrUtil { get; set; }
        public Nullable<decimal> NewSal { get; set; }
        public Nullable<decimal> NewHouseRnt { get; set; }
        public Nullable<decimal> IncPer { get; set; }
        public Nullable<decimal> IncAmt { get; set; }
        public string RecomAuth { get; set; }
        public Nullable<decimal> TaxDeduction { get; set; }
        public Nullable<decimal> NetPayable { get; set; }
        public Nullable<System.DateTime> Deldate { get; set; }
        public bool delstatus { get; set; }
        public Nullable<System.DateTime> effdate { get; set; }
        public Nullable<decimal> newbasicsal { get; set; }
        public Nullable<decimal> newutil { get; set; }
        public Nullable<decimal> currbasicsal { get; set; }
        public Nullable<int> cid { get; set; }
        public Nullable<decimal> tax { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
    }
}
