//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurAdvance
    {
        public string AdvId { get; set; }
        public string AdvNo { get; set; }
        public Nullable<System.DateTime> AdvDate { get; set; }
        public Nullable<int> PayTypeId { get; set; }
        public string BankNo { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<bool> Posted { get; set; }
        public string Remarks { get; set; }
        public string supplierid { get; set; }
        public int CompNo { get; set; }
        public int BranchNo { get; set; }
        public string VoucherNo { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
    }
}
