//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderDetail
    {
        public string POId { get; set; }
        public int LineNo { get; set; }
        public System.DateTime PODate { get; set; }
        public string StoreUnitId { get; set; }
        public string ItemId { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string ItemType { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> BalanceQty { get; set; }
        public Nullable<int> ItemClearedStatus { get; set; }
        public Nullable<decimal> BalanceQtySaleInv { get; set; }
        public Nullable<int> ItemClearedStatusQtySaleInv { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
        public string RequisitionID { get; set; }
        public int CompNo { get; set; }
        public int BranchNo { get; set; }
        public string GrnID { get; set; }
        public decimal GrnBalanceQty { get; set; }
        public int GrnItemClearedStatus { get; set; }
        public System.DateTime GrnDate { get; set; }
        public decimal LstPurQty { get; set; }
        public string CostCenterId { get; set; }
    }
}
