//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseRequestDetail
    {
        public string PrId { get; set; }
        public int lineno { get; set; }
        public string ItemId { get; set; }
        public Nullable<decimal> PrQty { get; set; }
        public Nullable<decimal> EstAmount { get; set; }
        public Nullable<System.DateTime> EstDate { get; set; }
        public Nullable<decimal> NeedAmount { get; set; }
        public Nullable<System.DateTime> NeedDate { get; set; }
        public Nullable<decimal> BalanceNeedAmount { get; set; }
        public Nullable<int> ItemClearedStatus { get; set; }
        public Nullable<decimal> BalanceQty { get; set; }
        public Nullable<int> ItemClearedStatusQty { get; set; }
        public Nullable<decimal> BalanceQtyDellChall { get; set; }
        public Nullable<int> ItemClearStausDellChall { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
    }
}
