//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseRequest
    {
        public string PrId { get; set; }
        public string PrNo { get; set; }
        public Nullable<System.DateTime> PrDate { get; set; }
        public string Remarks { get; set; }
        public string PurId { get; set; }
        public string IndentRRNo { get; set; }
        public int CompNo { get; set; }
        public int BranchNo { get; set; }
        public string RequisitionID { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
    }
}
