//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseAgingTest
    {
        public int PurAgingTestID { get; set; }
        public string PInvoiceId { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> PurInvDate { get; set; }
        public string SupplierName { get; set; }
        public string ItemID { get; set; }
        public string ItemName { get; set; }
        public Nullable<decimal> ItemQty { get; set; }
        public Nullable<decimal> ItemRate { get; set; }
        public Nullable<decimal> AWSTax { get; set; }
        public Nullable<System.DateTime> ItemDueDate { get; set; }
        public Nullable<decimal> AmtAdjusted { get; set; }
        public Nullable<decimal> AmtBalance { get; set; }
        public Nullable<int> InvClearedStatus { get; set; }
        public Nullable<int> CompNo { get; set; }
        public Nullable<int> BranchNo { get; set; }
        public Nullable<decimal> InvRecCharged { get; set; }
        public Nullable<decimal> CurrentDueDays { get; set; }
        public Nullable<decimal> DueAmt { get; set; }
        public Nullable<decimal> NotDue { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<decimal> SaleReturnCharge { get; set; }
        public string SupplierId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> GetAmtStatus { get; set; }
        public Nullable<decimal> PreviousReceivable { get; set; }
        public Nullable<decimal> BalanceReceivable { get; set; }
        public Nullable<int> DeletionID { get; set; }
    }
}
