//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurDeliveryChallDetail
    {
        public string DeliveryChallId { get; set; }
        public int LineNo { get; set; }
        public string ItemId { get; set; }
        public decimal Quantity { get; set; }
        public string OrderType { get; set; }
        public string OrderNo { get; set; }
        public string POId { get; set; }
        public string RequisitionID { get; set; }
        public string Specification { get; set; }
        public string Comments { get; set; }
        public string BalanceQty { get; set; }
        public Nullable<int> ItemClearedStatus { get; set; }
        public string Unit { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
    }
}
