//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QdItemTransaction
    {
        public string GodownId { get; set; }
        public string ItemId { get; set; }
        public string ItemName { get; set; }
        public string DocumentNo { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string Packing { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public int Compno { get; set; }
        public int BranchNo { get; set; }
        public Nullable<int> ItemClass { get; set; }
        public decimal OBQuantity { get; set; }
        public decimal GRNQty { get; set; }
        public decimal IssQty { get; set; }
        public string CostCenterId { get; set; }
        public string CostCenterName { get; set; }
        public string StoreUnitId { get; set; }
        public string UnitName { get; set; }
        public decimal Rate { get; set; }
    }
}
