//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptBounce
    {
        public string ReceiptBounceID { get; set; }
        public Nullable<int> ReceiptBounceNo { get; set; }
        public string IrID { get; set; }
        public Nullable<System.DateTime> BoucnceDate { get; set; }
        public Nullable<int> CompNo { get; set; }
        public Nullable<int> BranchNo { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> GodownDiff { get; set; }
    }
}
