//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptsCommission
    {
        public decimal RId { get; set; }
        public string SaleInvId { get; set; }
        public string SaleInvNo { get; set; }
        public Nullable<System.DateTime> IrDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> RecType { get; set; }
        public Nullable<decimal> BalanceAmount { get; set; }
    }
}
