//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resign
    {
        public int ResigId { get; set; }
        public string EmpId { get; set; }
        public Nullable<int> DesigId { get; set; }
        public Nullable<int> DeptId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string AppAuth { get; set; }
        public Nullable<int> Status { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> EffctDate { get; set; }
        public string Reason { get; set; }
        public string RecomAuth { get; set; }
        public bool DelStatus { get; set; }
        public string DelDate { get; set; }
        public decimal fine { get; set; }
        public decimal adv { get; set; }
        public decimal tax { get; set; }
        public decimal sal { get; set; }
        public decimal net { get; set; }
        public decimal loan { get; set; }
        public decimal ded { get; set; }
        public Nullable<int> cid { get; set; }
        public decimal carpayment { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
    }
}
