//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestDay
    {
        public int Id { get; set; }
        public string EmpId { get; set; }
        public Nullable<int> DeptId { get; set; }
        public Nullable<int> DesigId { get; set; }
        public string currestday { get; set; }
        public Nullable<System.DateTime> restdt { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> Deldate { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
    }
}
