//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RmGrnReturnP
    {
        public string RmrID { get; set; }
        public string RMRNo { get; set; }
        public System.DateTime RmrDate { get; set; }
        public string GRNID { get; set; }
        public string StoreUnitId { get; set; }
        public string Remarks { get; set; }
        public int CompNo { get; set; }
        public int BranchNo { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public int DeletionID { get; set; }
    }
}
