//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RmGrnDetail
    {
        public string GRNID { get; set; }
        public int lineno { get; set; }
        public string GRNNO { get; set; }
        public System.DateTime GrnDate { get; set; }
        public string StoreUnitId { get; set; }
        public string ItemId { get; set; }
        public Nullable<decimal> QtyRec { get; set; }
        public Nullable<decimal> QtyRej { get; set; }
        public decimal QtyAcc { get; set; }
        public decimal Rate { get; set; }
        public string OrderId { get; set; }
        public string OrderType { get; set; }
        public string PrId { get; set; }
        public string POId { get; set; }
        public string RequisitionID { get; set; }
        public string CostCenterId { get; set; }
        public decimal ReqBlncQty { get; set; }
        public string ItemRemarks { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public System.DateTime SaveDate { get; set; }
        public int DeletionID { get; set; }
        public decimal BalanceQtyAcc { get; set; }
        public int ItemClearedStatusQty { get; set; }
        public int Compno { get; set; }
        public int Branchno { get; set; }
        public string SupplierId { get; set; }
        public int RepairItem { get; set; }
    }
}
