//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RmGrn
    {
        public string GRNID { get; set; }
        public string GRNNO { get; set; }
        public System.DateTime GrnDate { get; set; }
        public string DeliveryChallId { get; set; }
        public string Remarks { get; set; }
        public int CompNo { get; set; }
        public int BranchNo { get; set; }
        public string BiltyNo { get; set; }
        public string GIPNo { get; set; }
        public string Vehicel { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public System.DateTime SaveDate { get; set; }
        public int DeletionID { get; set; }
        public string StoreUnitId { get; set; }
        public decimal STaxAmt { get; set; }
        public decimal SEDAmt { get; set; }
        public decimal FreightAmt { get; set; }
    }
}
