//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RmGrnReturnPDetail
    {
        public string RmrId { get; set; }
        public int lineno { get; set; }
        public System.DateTime RmrDate { get; set; }
        public string GRNID { get; set; }
        public string StoreUnitId { get; set; }
        public string CostCenterId { get; set; }
        public string ItemId { get; set; }
        public decimal Qty { get; set; }
        public decimal Rate { get; set; }
        public string SupplierId { get; set; }
        public string RetrunReason { get; set; }
        public int LahTransferId { get; set; }
        public System.DateTime SaveDate { get; set; }
        public int DeletionID { get; set; }
        public int Compno { get; set; }
        public int Branchno { get; set; }
    }
}
