//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RMIssuePdetail
    {
        public string IssueId { get; set; }
        public int lineno { get; set; }
        public System.DateTime IssueDate { get; set; }
        public string StoreUnitId { get; set; }
        public string ItemId { get; set; }
        public string UOM { get; set; }
        public decimal Qty { get; set; }
        public decimal BalanceQty { get; set; }
        public Nullable<decimal> StockQtyBalance { get; set; }
        public decimal ItemStockQty { get; set; }
        public string CostCenterId { get; set; }
        public Nullable<System.DateTime> PrevIssueDate { get; set; }
        public string PrevIssuId { get; set; }
        public string PrevIssueReson { get; set; }
        public string NewIssueReason { get; set; }
        public int Compno { get; set; }
        public int Branchno { get; set; }
        public int LahTransferId { get; set; }
        public System.DateTime SaveDate { get; set; }
        public int DeletionID { get; set; }
        public int ItemClearStatus { get; set; }
    }
}
