//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryDetail
    {
        public string SalaryId { get; set; }
        public int LineNo { get; set; }
        public Nullable<decimal> BasicSal { get; set; }
        public Nullable<decimal> HouseRent { get; set; }
        public Nullable<decimal> Utilities { get; set; }
        public Nullable<decimal> Convance { get; set; }
        public Nullable<decimal> Other { get; set; }
        public Nullable<decimal> GrossSalary { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> SaleTaxDate { get; set; }
        public Nullable<System.DateTime> AplicalbeDate { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
    
        public virtual SalaryMaster SalaryMaster { get; set; }
    }
}
