//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleTaxSumup
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> TaxDate { get; set; }
        public Nullable<decimal> Sales { get; set; }
        public Nullable<decimal> SalesTax { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> CompNo { get; set; }
        public Nullable<int> BranchNo { get; set; }
    }
}
