//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleAdvance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SaleAdvance()
        {
            this.SaleAdvanceAdjustmentDetails = new HashSet<SaleAdvanceAdjustmentDetail>();
        }
    
        public string AdvanceId { get; set; }
        public Nullable<int> AdvanceNO { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<int> PayTypeId { get; set; }
        public string BankNo { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<int> Posted { get; set; }
        public string Remarks { get; set; }
        public string CustomerNo { get; set; }
        public Nullable<int> CompNo { get; set; }
        public Nullable<int> BranchNo { get; set; }
        public Nullable<int> GetAmtStatus { get; set; }
        public Nullable<int> AdvanceNoGen { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
        public string GodownId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleAdvanceAdjustmentDetail> SaleAdvanceAdjustmentDetails { get; set; }
    }
}
