//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SaleInvoice()
        {
            this.SaleAdvanceAdjustments = new HashSet<SaleAdvanceAdjustment>();
            this.SaleInvoiceDetails = new HashSet<SaleInvoiceDetail>();
        }
    
        public string SaleInvId { get; set; }
        public decimal SaleInvNo { get; set; }
        public string CustomerNo { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public Nullable<System.DateTime> SDate { get; set; }
        public Nullable<decimal> TAmount { get; set; }
        public string Remarks { get; set; }
        public string DelChallanId { get; set; }
        public Nullable<int> PaymentID { get; set; }
        public string AdvanceID { get; set; }
        public Nullable<decimal> AdvanceCharged { get; set; }
        public int CompNo { get; set; }
        public int BranchNo { get; set; }
        public Nullable<int> Paid { get; set; }
        public decimal PAmount { get; set; }
        public decimal BAmount { get; set; }
        public string DisplayInvoiceNumber { get; set; }
        public string BranchCode { get; set; }
        public string BankAccount { get; set; }
        public Nullable<decimal> TotalValExSaleTax { get; set; }
        public Nullable<decimal> TotalSaleTaxPayable { get; set; }
        public Nullable<decimal> TotalValIncSaleTax { get; set; }
        public string SalesManId { get; set; }
        public Nullable<decimal> TotalQtyInvoice { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public string GodownId { get; set; }
        public string DeliverdOrExFactory { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public string OpeningBalanceID { get; set; }
        public Nullable<int> DeletionID { get; set; }
        public Nullable<int> DebitCheck { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleAdvanceAdjustment> SaleAdvanceAdjustments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleInvoiceDetail> SaleInvoiceDetails { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
