//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleDebitNote
    {
        public string DebitNoteID { get; set; }
        public Nullable<int> DebitNoteNum { get; set; }
        public Nullable<System.DateTime> DebitNoteDate { get; set; }
        public string DellChallanID { get; set; }
        public string CustomerID { get; set; }
        public string Description { get; set; }
        public Nullable<int> CompNo { get; set; }
        public Nullable<int> BranchNo { get; set; }
        public string Remarks { get; set; }
        public string FreightAcntID { get; set; }
        public Nullable<decimal> AmountCharged { get; set; }
        public Nullable<decimal> AmountBalance { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<int> Paid { get; set; }
        public Nullable<System.DateTime> ItemDueDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
    }
}
