//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleAdvanceAdjustmentDetail
    {
        public string AdvAdjId { get; set; }
        public int LineNum { get; set; }
        public string AdvanceId { get; set; }
        public decimal OrignalAmount { get; set; }
        public decimal AvailableAmount { get; set; }
        public decimal AmountCharged { get; set; }
        public decimal AmountBalance { get; set; }
        public int Paid { get; set; }
        public System.DateTime Savedate { get; set; }
        public Nullable<int> DeletionId { get; set; }
        public int LahTransferId { get; set; }
    
        public virtual SaleAdvance SaleAdvance { get; set; }
        public virtual SaleAdvanceAdjustment SaleAdvanceAdjustment { get; set; }
    }
}
