//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleInvoiceDetail
    {
        public string SaleInvId { get; set; }
        public int LineNo { get; set; }
        public string ItemId { get; set; }
        public decimal SQty { get; set; }
        public Nullable<decimal> SaleRate { get; set; }
        public Nullable<decimal> AmtWoSt { get; set; }
        public Nullable<decimal> AmtWSt { get; set; }
        public Nullable<decimal> SaleTax { get; set; }
        public Nullable<decimal> AdditionalSaleTax { get; set; }
        public Nullable<System.DateTime> ItemDueDate { get; set; }
        public Nullable<decimal> SaleTaxRate { get; set; }
        public Nullable<decimal> ASaleTaxRate { get; set; }
        public string PaymentAccount { get; set; }
        public string ItemClearStatus { get; set; }
        public Nullable<decimal> InvQtyBalance { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<int> DueDays { get; set; }
        public Nullable<decimal> ASaleTaxRateRec { get; set; }
        public Nullable<decimal> SaleTaxRat { get; set; }
        public decimal NewAmtWoSt { get; set; }
        public decimal NewAmtWSt { get; set; }
        public Nullable<decimal> NewAdditionalSaleTax { get; set; }
        public decimal NewSaleTax { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
        public string SaleQtyDisplay { get; set; }
        public Nullable<decimal> DbitInvQtyBalance { get; set; }
        public Nullable<int> DebitInvoiceClearStatus { get; set; }
        public Nullable<decimal> InvRateBalance { get; set; }
        public Nullable<int> ItemRateClearStatus { get; set; }
        public decimal ExcDuty { get; set; }
        public decimal ExcDutyAmt { get; set; }
        public decimal SPDrate { get; set; }
        public decimal SPDAmount { get; set; }
        public string DelChallanId { get; set; }
    
        public virtual SaleInvoice SaleInvoice { get; set; }
    }
}
