//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleAdvanceAdjustment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SaleAdvanceAdjustment()
        {
            this.SaleAdvanceAdjustmentDetails = new HashSet<SaleAdvanceAdjustmentDetail>();
        }
    
        public string AdvAdjId { get; set; }
        public decimal AdvAdjNo { get; set; }
        public System.DateTime AdvAdjDate { get; set; }
        public string Remarks { get; set; }
        public string CustomerNo { get; set; }
        public string SaleInvId { get; set; }
        public decimal InvAmount { get; set; }
        public decimal InvPaid { get; set; }
        public decimal InvBalance { get; set; }
        public decimal AdvanceTotalAmount { get; set; }
        public int CompNo { get; set; }
        public int BranchNo { get; set; }
        public int LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public int DeletionId { get; set; }
        public string GodownID { get; set; }
    
        public virtual SaleInvoice SaleInvoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleAdvanceAdjustmentDetail> SaleAdvanceAdjustmentDetails { get; set; }
    }
}
