//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesCommReport
    {
        public decimal InvId { get; set; }
        public string SaleInvId { get; set; }
        public string SaleInvNo { get; set; }
        public Nullable<System.DateTime> SDate { get; set; }
        public string CustomerNo { get; set; }
        public string CustomerName { get; set; }
        public string ItemId { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> DueDays { get; set; }
        public Nullable<System.DateTime> ItemDueDate { get; set; }
        public Nullable<decimal> NewAmtWoSt { get; set; }
        public Nullable<decimal> SQty { get; set; }
        public string SalesManId { get; set; }
        public string SalesManName { get; set; }
        public Nullable<decimal> IAmount { get; set; }
        public Nullable<System.DateTime> IrDate { get; set; }
        public Nullable<decimal> ReceiptAmount { get; set; }
        public Nullable<int> RecType { get; set; }
        public Nullable<int> CompNo { get; set; }
        public Nullable<int> BranchNo { get; set; }
        public Nullable<int> OverDays { get; set; }
        public Nullable<decimal> CommissionRate { get; set; }
        public Nullable<decimal> CommissionAmount { get; set; }
        public Nullable<int> MarginDays { get; set; }
        public Nullable<int> SaleTaxRate { get; set; }
    }
}
