//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleAgingTest
    {
        public int SaleAgingRecID { get; set; }
        public string SaleInvId { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> SaleInvDate { get; set; }
        public string CustomerName { get; set; }
        public string ItemID { get; set; }
        public string ItemName { get; set; }
        public Nullable<decimal> ItemQty { get; set; }
        public Nullable<decimal> ItemRate { get; set; }
        public Nullable<decimal> AWSTax { get; set; }
        public Nullable<System.DateTime> ItemDueDate { get; set; }
        public Nullable<decimal> DueDays { get; set; }
        public Nullable<decimal> AmtAdjusted { get; set; }
        public Nullable<decimal> AmtBalance { get; set; }
        public Nullable<int> InvClearedStatus { get; set; }
        public Nullable<decimal> AdvanceAmtCharg { get; set; }
        public Nullable<decimal> AdvanceBalance { get; set; }
        public Nullable<int> CompNo { get; set; }
        public Nullable<int> BranchNo { get; set; }
        public Nullable<decimal> InvRecCharged { get; set; }
        public Nullable<decimal> SaleAvanceReCharg { get; set; }
        public Nullable<decimal> CurrentDueDays { get; set; }
        public Nullable<decimal> C0_15 { get; set; }
        public Nullable<decimal> C16_45 { get; set; }
        public Nullable<decimal> C46_60 { get; set; }
        public Nullable<decimal> C61_75 { get; set; }
        public Nullable<decimal> C76_90 { get; set; }
        public Nullable<decimal> C91_120 { get; set; }
        public Nullable<decimal> C120_ { get; set; }
        public Nullable<decimal> DueAmt { get; set; }
        public Nullable<decimal> NotDue { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public string SalesManId { get; set; }
        public string SalesManName { get; set; }
        public Nullable<decimal> SaleReturnCharge { get; set; }
        public string CustomerID { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> GetAmtStatus { get; set; }
        public Nullable<decimal> PreviousReceivable { get; set; }
        public Nullable<decimal> BalanceReceivable { get; set; }
        public Nullable<int> DeletionID { get; set; }
        public string GodownId { get; set; }
        public decimal C0_30 { get; set; }
        public decimal C31_60 { get; set; }
        public decimal C61_90 { get; set; }
    }
}
