//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SControlAcnt
    {
        public string USubAcntId { get; set; }
        public string USubDscr { get; set; }
        public Nullable<int> LahTransferId { get; set; }
    }
}
