//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxRate
    {
        public int TaxId { get; set; }
        public string Crit { get; set; }
        public Nullable<decimal> FLimit { get; set; }
        public Nullable<decimal> TLimit { get; set; }
        public Nullable<double> Per { get; set; }
        public Nullable<decimal> DedAmt { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
    }
}
