//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGLProfitLossAccountSum
    {
        public decimal Sale { get; set; }
        public decimal SaleTaxes { get; set; }
        public decimal CostSale { get; set; }
        public decimal AdminExpense { get; set; }
        public decimal SellingExpense { get; set; }
        public decimal FinancialCost { get; set; }
        public decimal OtherIncome { get; set; }
        public decimal OthOperCharges { get; set; }
        public decimal ProvisionForTaxation { get; set; }
        public System.DateTime fdate { get; set; }
        public System.DateTime tdate { get; set; }
    }
}
