//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGLBalanceSheetAccountSum
    {
        public decimal UnAppropriatedProfit { get; set; }
        public decimal CapitalNReserve { get; set; }
        public decimal LongTremLoanFinance { get; set; }
        public decimal Liabilities { get; set; }
        public decimal TradeandOtherPay { get; set; }
        public decimal IntrstNdMarkupAccured { get; set; }
        public decimal ShrtTermBorrowing { get; set; }
        public decimal CrntPrtionofLngTrmBorowing { get; set; }
        public decimal PrvisnForTaxation { get; set; }
        public decimal PrptyPlntNdEquipment { get; set; }
        public decimal StoreNSpares { get; set; }
        public decimal StockInTrade { get; set; }
        public decimal Debtors { get; set; }
        public decimal AdvDeposits { get; set; }
        public decimal TrdDpstNdShrtTrnPmnt { get; set; }
        public decimal CashNBankBlnc { get; set; }
        public int CompNo { get; set; }
        public int BranchNo { get; set; }
        public System.DateTime SaveDate { get; set; }
        public int LahTransferId { get; set; }
        public int DeletionId { get; set; }
        public System.DateTime Fdate { get; set; }
        public System.DateTime TDate { get; set; }
    }
}
