//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGLAssetAccount
    {
        public string AssetId { get; set; }
        public string FixAssetAcntId { get; set; }
        public string AccDepecAcntId { get; set; }
        public decimal Rate { get; set; }
        public string Type { get; set; }
        public int CompNo { get; set; }
        public int BranchNo { get; set; }
        public System.DateTime SaveDate { get; set; }
        public int LahTransferId { get; set; }
        public int DeletionId { get; set; }
        public decimal FixAssetOpeningBalance { get; set; }
        public decimal AccDepecClosingBalance { get; set; }
        public decimal FixAssetClosingBalance { get; set; }
    }
}
