//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSupplierBuyer
    {
        public string STRegNoSupplier { get; set; }
        public string SupplierName { get; set; }
        public string RegAddress { get; set; }
        public string STRegNo { get; set; }
        public string SupplierRBuyer { get; set; }
        public int CompNo { get; set; }
        public int BranchNo { get; set; }
        public int Reg { get; set; }
    }
}
