//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeReport
    {
        public decimal TId { get; set; }
        public string EmpId { get; set; }
        public Nullable<decimal> AverageTimeIn { get; set; }
        public Nullable<decimal> AverageTimeOut { get; set; }
        public string Name { get; set; }
        public string CompDesc { get; set; }
        public string DeptDesc { get; set; }
        public Nullable<System.DateTime> fdate { get; set; }
        public Nullable<System.DateTime> tdate { get; set; }
        public Nullable<decimal> WorkingDays { get; set; }
        public Nullable<int> LeavesAvailed { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
    }
}
