//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfer
    {
        public int TransId { get; set; }
        public string EmpId { get; set; }
        public Nullable<int> DesigId { get; set; }
        public Nullable<int> PresDeptId { get; set; }
        public Nullable<int> NewDeptId { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<int> FCompId { get; set; }
        public Nullable<int> TCompId { get; set; }
        public string RecomId { get; set; }
        public string AppId { get; set; }
        public bool DelStatus { get; set; }
        public Nullable<System.DateTime> DelDate { get; set; }
        public Nullable<int> NewDesig { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
    }
}
