//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRight
    {
        public int UserID { get; set; }
        public Nullable<int> CheckItems { get; set; }
        public Nullable<int> CheckSalesMan { get; set; }
        public Nullable<int> CheckBank { get; set; }
        public Nullable<int> CheckBrand { get; set; }
        public Nullable<int> CheckPriceList { get; set; }
        public Nullable<int> CheckFgGodown { get; set; }
        public Nullable<int> CheckAcntInfo { get; set; }
        public Nullable<int> CheckType { get; set; }
        public Nullable<int> CheckPurchaser { get; set; }
        public Nullable<int> CheckSupplier { get; set; }
        public Nullable<int> CheckCountry { get; set; }
        public Nullable<int> CheckCurrency { get; set; }
        public Nullable<int> CheckInvoiceTerms { get; set; }
        public Nullable<int> CheckCustomer { get; set; }
        public Nullable<int> CheckPaymentType { get; set; }
        public Nullable<int> CheckOpeningBalanceRM { get; set; }
        public Nullable<int> CheckGoodReceiptNoteRM { get; set; }
        public Nullable<int> CheckGoodReturnNote { get; set; }
        public Nullable<int> CheckGoodIssueNote { get; set; }
        public Nullable<int> CheckOpeningBalanceFG { get; set; }
        public Nullable<int> CheckGoodReceiptNoteFG { get; set; }
        public Nullable<int> CheckDelliveryChallanFG { get; set; }
        public Nullable<int> CheckStockTransferFG { get; set; }
        public Nullable<int> CheckSaleInvoice { get; set; }
        public Nullable<int> CheckSaleReturn { get; set; }
        public Nullable<int> CheckSaleAdvanceRecived { get; set; }
        public Nullable<int> CheckSaleInvoiceReceipt { get; set; }
        public Nullable<int> CheckRequisitonOrder { get; set; }
        public Nullable<int> CheckCashPurchaseRequest { get; set; }
        public Nullable<int> CheckPurchaseOrder { get; set; }
        public Nullable<int> CheckDelliveryChallan { get; set; }
        public Nullable<int> CheckPurchaseInvoice { get; set; }
        public Nullable<int> CheckPurchaseReturn { get; set; }
        public Nullable<int> CheckPurchaseAdvancePaid { get; set; }
        public Nullable<int> CheckInvoicePayment { get; set; }
        public Nullable<int> CheckAdvanceToPurchaser { get; set; }
        public Nullable<int> CeckInventoryReports { get; set; }
        public Nullable<int> CheckSaleReports { get; set; }
        public Nullable<int> CheckPurchaseReports { get; set; }
        public Nullable<int> ChckOthPInvoice { get; set; }
        public Nullable<int> CompNo { get; set; }
        public Nullable<int> BranchNo { get; set; }
    }
}
