//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visite
    {
        public int VisiteId { get; set; }
        public string EmpId { get; set; }
        public Nullable<System.DateTime> TimeIn { get; set; }
        public Nullable<System.DateTime> TimeOut { get; set; }
        public Nullable<int> DeptId { get; set; }
        public Nullable<int> DesigId { get; set; }
        public string Location { get; set; }
        public string Vehice { get; set; }
        public Nullable<System.DateTime> VisDate { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public bool visdelestatus { get; set; }
        public Nullable<System.DateTime> visdeledate { get; set; }
        public Nullable<System.DateTime> totaltime { get; set; }
        public Nullable<int> cid { get; set; }
        public Nullable<System.DateTime> dt { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
    }
}
