//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPStandard.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoucherType
    {
        public string VourcherTypeId { get; set; }
        public string Dscr { get; set; }
        public Nullable<decimal> DrBalance { get; set; }
        public Nullable<decimal> CrBalance { get; set; }
        public Nullable<int> LahTransferId { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> DeletionID { get; set; }
        public Nullable<int> VoucherActivity { get; set; }
        public Nullable<System.DateTime> VoucherTiming { get; set; }
    }
}
